apiVersion: v1
kind: Service
metadata:
  name: aiop-server-nodeport
  namespace: aios-system
  labels: { app: aiop, component: server }
spec:
  selector: { app: aiop, component: server }
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
