apiVersion: v1
kind: Service
metadata:
  name: aiop-server-nodeport
  namespace: aiop-dev
  labels: { app: aiop, component: server }
spec:
  selector: { app: aiop, component: server }
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30083
